# http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html
sensio_framework_extra:
    router:
        annotations: true
    request:
        converters: true
        auto_convert: true
    view:
        annotations: true
    cache:
        annotations: true
    security:
        annotations: true
    psr_message:
        enabled: false
