jms_serializer:
    visitors:
        json:
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_UNESCAPED_UNICODE
                - JSON_PRESERVE_ZERO_FRACTION
